import { StyleSheet } from 'react-native';
import { isiPhoneX ,WINDOW } from './util';

const publics = StyleSheet.create({
    flex1:{flex:1},
    navImageSize:{width:25,height:25},
    backSize:{width:18,height:18},
    nextSize:{width:14,height:14},
    downSize:{width:10,height:10},
    produceImageSize:{width:120,height:80},
    ItemIconSize:{width:22,height:22},
    homeTypeImageSize:{width:50,height:50},
    messageIconSize:{width:40,height:40},
    typeNewsImageSize:{width:36},
    iPhoneX:{flex:1,backgroundColor:'#fff',marginTop:isiPhoneX() ? -60 : 0},
    bannerStyleHeight:{height: isiPhoneX() ? 230 : 170},
    modulesTitleBackgroundWidth:{width:70},
    modulesImageSize:{width:120,height:80},
    width100:{width:WINDOW.width},
    debug:{backgroundColor: 'red'},
    color333:{color:'#333'},
    color6d:{color:'#6d6d6d'},
    colorHome:{color:'#ff6934'},
    colorWhite:{color:'white'},
    colorFd:{color:'#fd5353'},
    colorEf:{color:'#ef322d'},
    color40:{color:'#40aafc'},
    color5d:{color:'#5b91e3'},
    color1c:{color:'#1c8ffa'},
    font_1:{fontSize:10},
    font_2:{fontSize:12},
    font_3:{fontSize:14},
    font_4:{fontSize:16},
    font_5:{fontSize:18},
    font_6:{fontSize:20},
    font_8:{fontSize:30},
    textAlignCenter:{textAlign:'center'},
    height36:{height:36},
    height40:{height:40},
    height56:{height:56},
    height60:{height:60},
    height70:{height:70},
    borderTop:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#dbdbdb'},
    borderBottom:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#dbdbdb'},
    paddingTop3:{paddingTop:3},
    paddingTopPercentage2:{paddingTop:'2%'},
    paddingTopPercentage3:{paddingTop:'3%'},
    paddingTopPercentage5:{paddingTop:'5%'},
    marginTopAndBottomPercentage5:{marginTop:'5%',marginBottom:'5%'},
    marginTopAndBottom5:{marginTop:5,marginBottom:5},
    marginTopAndBottom15:{marginTop:15,marginBottom:15},
    marginTop1:{marginTop:'1%'},
    marginBottom1:{marginBottom:'1%'},
    paddingTopAndBottom1_3:{paddingTop:'2%',paddingBottom:'2%'},
    paddingBottom_15:{paddingBottom:15},
    paddingBottom_10:{paddingBottom:10},
    paddingBottom10:{paddingBottom:'10%'},
    paddingBottom1_5:{paddingBottom:"1.5%"},
    paddingBottom2:{paddingBottom:"2%"},
    paddingTopAndBottom2:{paddingTop:'2%',paddingBottom:'2%'},
    paddingTopAndBottom1:{paddingTop:'1%',paddingBottom:'1%'},
    paddingTopAndBottom3:{paddingTop:'3%',paddingBottom:'3%'},
    paddingTopAndBottom5:{paddingTop:'5%',paddingBottom:'5%'},
    paddingLeftAndRight2:{paddingLeft:'2%',paddingRight:'2%'},
    paddingLeftAndRight3:{paddingLeft:'3%',paddingRight:'3%'},
    paddingLeftAndRight4:{paddingLeft:'4%',paddingRight:'4%'},
    paddingLeft3AndRight8:{paddingLeft:'3%',paddingRight:'8%'},
    paddingLeft3:{paddingLeft:'3%'},
    paddingLeft3px:{paddingLeft:3},
    paddingRight3px:{paddingRight:3},
    paddingLeft5:{paddingLeft:'5%'},
    paddingRight2:{paddingRight:'2%'},
    paddingRight3:{paddingRight:'3%'},
    paddingLeftAndRight5:{paddingLeft:'5%',paddingRight:'5%'},
    paddingLeftAndRight15:{paddingLeft:15,paddingRight:15},
    padding10px:{paddingLeft:10,paddingTop:8,paddingBottom:8},
    paddingLeft15:{paddingLeft:15},
    marginLeftAndRight5:{marginLeft:'5%',marginRight:'5%'},
    marginLeft3:{marginLeft:'3%'},
    marginTop3:{marginTop:'3%'},
    marginBottom2:{marginBottom:'2%'},
    marginBottom3:{marginBottom:'3%'},
    marginBottom4:{marginBottom:'4%'},
    marginBottom5:{marginBottom:'5%'},
    paddingLeftAndRight8:{paddingLeft:'8%',paddingRight:'8%'},
    paddingLeftAndRight10:{paddingLeft:'10%',paddingRight:'10%'},
    flexRowCenter:{flexDirection: 'row',justifyContent:'space-between',alignItems:'center'},
    flexRowCenterAround:{flexDirection: 'row',justifyContent:'space-around',alignItems:'center'},
    flexRowCenterFlexStart:{flexDirection: 'row',justifyContent:'flex-start',alignItems:'center'},
    flexRowCenterFlexEnd:{flexDirection: 'row',justifyContent:'flex-start',alignItems:'flex-end'},
    flexRowCenterCenter:{flexDirection: 'row',justifyContent:'center',alignItems:'center'},
    flexRowCenterEnd:{flexDirection: 'row',justifyContent:'center',alignItems:'flex-end'},
    flexRowEndFlexStart:{flexDirection: 'row',justifyContent:'flex-start',alignItems:'flex-end'},
    flexRowEndStart:{flexDirection: 'column',justifyContent:'flex-start',alignItems:'flex-start'},
    flexRowStart:{flexDirection: 'row',justifyContent:'flex-start'},
    flexColumnStart:{flexDirection: 'column',justifyContent:'flex-start',alignItems:'flex-start'},
    flexColumnCenter:{flexDirection: 'column',justifyContent:'center'},
    flexColumnCenterCenter:{flexDirection: 'column',justifyContent:'center',alignItems:'center'},
    flexColumnFlexStart:{flexDirection: 'column',justifyContent:'flex-start'},
    flexColumnFlexStartItemCenter:{flexDirection: 'column',justifyContent:'flex-start',alignItems:'center'},
    flexColumnAlignCenter:{flexDirection: 'column',justifyContent:'center',alignContent:'center'},
    iconSize15:{width:15},
    iconSize18:{width:18},
    iconSize20:{width:20},
    iconSize22:{width:22},
    iconSize24:{width:24},
    iconSize25:{width:25},
    backgroundColorWhite:{backgroundColor:'white'},
    backgroundColorDbdbdb:{backgroundColor:'#dbdbdb'},
    header:{paddingTop:isiPhoneX() ? 60 : 10,paddingRight:15,paddingLeft:15,paddingBottom:15,position:'relative'},
    headerIconSize:{width:24,height:24},
    headerTitle:{color:'white',fontSize:18},
    fontWeight:{fontWeight:'bold'},
    leftWhiteBack:{borderTopWidth:1,borderLeftWidth:1,borderColor:"white"},
    itemHeight:{height:50},
    borderRadius5:{borderRadius:5},
    deg90:{transform: [{rotate:'-180deg'}]}
});
export default publics;